"""
Problem Statement at: https://www.hackerrank.com/challenges/30-testing/problem
"""


"""Begin Auto Generated Code"""
def minimum_index(seq):
    if len(seq) == 0:
        raise ValueError("Cannot get the minimum value index from an empty sequence")
    min_idx = 0
    for i in range(1, len(seq)):
        if seq[i] < seq[min_idx]:
            min_idx = i
    return min_idx


"""End Auto Generated Code"""

"""
Each of the Following classes and their methods were autogenerated, the problem statement was to fill in the 
methods to conform to passing or failing test cases. The definition of those test cases can be found on the problem
statement page
"""


class TestDataEmptyArray(object):

    @staticmethod
    def get_array():
        return []


class TestDataUniqueValues(object):

    @staticmethod
    def get_array():
        return [5, 4, 3, 1, 2]

    @staticmethod
    def get_expected_result():
        return 3


class TestDataExactlyTwoDifferentMinimums(object):

    @staticmethod
    def get_array():
        return [1, 5, 4, 1, 2]

    @staticmethod
    def get_expected_result():
        return 0

